In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [5]:
# First rows
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [6]:
# Number of rows and columns
print("Shape:", order_reviews.shape)

# Column names
print("Columns:", order_reviews.columns.tolist())

# Data types and non-null counts
order_reviews.info()

# Statistical summary
order_reviews.describe()

Shape: (99224, 7)
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [10]:
date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_columns:
    order_reviews[col] = pd.to_datetime(
        order_reviews[col],
        errors="coerce"
    )

print(order_reviews[date_columns].dtypes)

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [7]:
#counts missing values in each column
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [9]:
print(order_reviews["review_score"].value_counts().sort_index())

print("\nReview score percentages:")
print(
    (order_reviews["review_score"].value_counts(normalize=True)
     .sort_index() * 100).round(2)
)

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

Review score percentages:
review_score
1    11.51
2     3.18
3     8.24
4    19.29
5    57.78
Name: proportion, dtype: float64

In [8]:
#check for exact duplicate rows
order_reviews.duplicated().sum()

np.int64(0)

In [11]:
order_reviews_clean = order_reviews.copy()

order_reviews_clean.to_csv(
    "order_reviews_clean.csv",
    index=False
)